// Style reminder: Sobha-inspired editorial pacing — image-led hero, quiet luxury typography, story-first transitions, a community showcase rail, editorial highlights, and generous copy blocks. Royal Swiss City copy is original and intentionally expanded.
import { useEffect, useState } from "react";
import { ChevronDown, ChevronRight, Menu, X, ArrowDown, Instagram, Facebook, Linkedin, Youtube } from "lucide-react";
import { ArchedSheet } from "@/components/ArchivedSheet";

const img = { logo: "https://royal-swiss-city-30.vercel.app/logo.png", hero: "/city-aerial.jpg", city: "/city-aerial.jpg", developer: "/hrl-highrise.jpg", green: "/green-energy.jpg", chairman: "/chairman.png", ceo: "/ceo.png", partnership: "/infrastructure.jpg", residences: "/hrl-roads.jpg", aerial: "/city-aerial.jpg" };
const nav = ["HOME", "THE CITY", "DEVELOPER", "LOCATION", "FAQ", "PARTNER", "DEALER" ,"ENQUIRE"];
const navMobile = ["HOME", "THE CITY", "DEVELOPER", "PROJECTS", "LOCATION", "FAQ", "PARTNER", "DEALER" ,"ENQUIRE"];
const footerLinks = ["Residential Plots", "Commercial Plots", "The City", "Developer", "Location", "FAQ", "Partner", "Enquire"];
const footerDescriptions = {
  "Residential Plots": " MARLA 3.5 MARLA 5 MARLA 10 KANAL 1 KANAL 2",
  "Commercial Plots": "MARLA 2\nMARLA 4\nMARLA 8",
  "The City": "Discover a considered way to experience the city at Royal Swiss City.",
  "Developer": "Discover a considered way to experience developer at Royal Swiss City.",
  "Location": "Discover a considered way to experience location at Royal Swiss City.",
  "FAQ": "Discover a considered way to experience faq at Royal Swiss City.",
  "Partner": "Discover a considered way to experience partner at Royal Swiss City.",
  "Enquire": "Discover a considered way to experience enquire at Royal Swiss City."
};
const communityCards = [
  { eyebrow: "THE RIVERFRONT", title: "Invest In Your Future", body: "A structured payment plan, riverfront land, and the credibility of HRL behind every plot. Details available from our sales team.", image: img.aerial },
  { eyebrow: "THE NEIGHBOURHOOD", title: "Become An Austhorized Partner", body: "Join the official Royal Swiss City dealer network. Sales support, marketing materials, and a professional partnership framework.", image: img.city },
  { eyebrow: "THE HOME", title: "Space for what matters.", body: "A Swiss-inspired setting for families, investors, and future generations to make their own.", image: img.residences },
];
const features = ["Gated Community", "Solar Infrastructure", "Riverfront Setting", "Wide Boulevards", "Education & Healthcare", "Retail & Services", "Sports & Recreation", "Water Management"];
const numbers = [{ value: "60+", label: "YEARS OF EXPERIENCE" }, { value: "140,000", label: "ACRES IN THE RAVI VISION" }, { value: "46 KM", label: "RIVERFRONT HORIZON" }, { value: "10M+", label: "FUTURE RESIDENTS" }];
function Logo() { return <img className="brand-logo" src={img.logo} alt="Royal Swiss City" /> }
function Anchor({ item }: { item: string }) { 
  if (item === "DEVELOPER") {
    return <a href="/developer">{item}</a>
  }
  if (item === "HOME") {
    return <a href="/">{item}</a>
  }
  if (item === "PROJECTS") {
    return <a href="/projects">{item}</a>
  }
  return <a href={`#${item.toLowerCase().replaceAll(" ", "-")}`}>{item}</a> 
}
export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [scrollY, setScrollY] = useState(0); const [openFooter, setOpenFooter] = useState<string | null>(null);
  useEffect(() => { let f = 0; const fn = () => { cancelAnimationFrame(f); f = requestAnimationFrame(() => { setScrollY(window.scrollY); setScrolled(window.scrollY > 28) }) }; fn(); window.addEventListener("scroll", fn, { passive: true }); return () => { cancelAnimationFrame(f); window.removeEventListener("scroll", fn) } }, []);
  useEffect(() => { const o = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && e.target.classList.add("is-visible")), { threshold: .12, rootMargin: "0px 0px -10% 0px" }); document.querySelectorAll(".reveal-section,.reveal-item").forEach(n => o.observe(n)); return () => o.disconnect() }, []);
  const vh = typeof window !== "undefined" ? window.innerHeight : 800; const heroProgress = Math.min(scrollY / Math.max(vh, 800), 1); const railProgress = Math.min(Math.max((scrollY - vh * 2.3) / 700, 0), 1);
  return <main className="walkthrough-page" style={{ "--hero-progress": heroProgress } as React.CSSProperties}>
    <header className={`walk-header ${scrolled ? "is-scrolled" : ""}`}><button className="mobile-menu-trigger" aria-label="Menu" onClick={() => setMenuOpen(true)}><Menu size={22} strokeWidth={1.4} /></button><nav className="desktop-links desktop-links--left">{nav.slice(0, 3).map(item => <Anchor key={item} item={item} />)}</nav><a className="centered-brand" href="#home"><Logo /></a><nav className="desktop-links desktop-links--right">{nav.slice(3).map(item => <Anchor key={item} item={item} />)}</nav></header>
    <section id="home" className="walk-hero reveal-section"><picture><img src={img.hero} alt="Royal Swiss City riverfront masterplan in Lahore" /></picture><div className="hero-shade" /><div className="hero-copy"><p className="hero-kicker">RAVI RIVERFRONT · LAHORE · PAKISTAN</p><h1>ROYAL<br /><span>SWISS</span><br />CITY</h1><p>A riverfront community designed for the life ahead.<br />A new address with space to unfold.</p><a href="#the-city">DISCOVER THE CITY</a></div><div className="hero-scroll"><span>SCROLL TO EXPLORE</span><ArrowDown size={14} /></div></section>
    <ArchedSheet />

    <section id="vision" className="vision-scene reveal-section"><div className="section-index">02 / 08</div><div className="vision-copy"><p className="section-kicker">THE RIVERFRONT VISION</p><h2>The river shapes<br /><em>the horizon.</em></h2><p>Lahore is growing toward the Ravi. Around that movement, a new urban idea is taking shape: a greener, more connected city where water, landscape, neighbourhoods, and opportunity belong to the same long view.</p><p>Royal Swiss City is positioned within that story — not as a passing development, but as an address designed to mature with the city around it.</p></div><div className="metric-grid">{numbers.map((n, i) => <div className="metric reveal-item" key={n.label} style={{ transitionDelay: `${i * 90}ms` }}><strong>{n.value}</strong><span>{n.label}</span></div>)}</div></section>
    <section id="developer" className="developer-section reveal-section"><div className="developer-image"><img src={img.developer} alt="Habib Rafiq engineering and construction legacy" /></div><div className="developer-copy"><p className="section-kicker">03 / DEVELOPER</p><h2>CRAFTED BY<br /><em>EXPERIENCE.</em></h2><p>Behind Royal Swiss City is a legacy built over six decades. Habib Rafiq and RKS bring the discipline of engineering, infrastructure, and delivery to a new kind of residential address.</p><p>That experience is felt in the decisions that matter: the scale of the roads, the care in the utilities, the clarity of the masterplan, and the confidence that comes from building for the long term.</p><div className="stat-line"><span>1962<small>THE JOURNEY BEGAN</small></span><span>60+<small>YEARS OF DELIVERY</small></span></div><a href="#leadership">MEET THE PEOPLE <ChevronRight size={13} /></a></div></section>
    <section id="leadership" className="leadership-section reveal-section"><div className="leadership-heading"><p className="section-kicker">04 / A SHARED VISION</p><h2>PEOPLE WHO<br /><em>BUILD FORWARD.</em></h2><p>Every enduring place begins with a belief in what it can become. The leadership behind Royal Swiss City carries that belief into every decision — combining national experience with a clear view of Lahore’s future.</p></div><div className="leaders"><article className="leader-card reveal-item"><img src={img.chairman} alt="Shahid Rafiq" /><div><small>CHAIRMAN</small><h3>Shahid Rafiq</h3><p>A career shaped by innovation, quality, and the patient work of turning ambitious infrastructure into lasting places.</p></div></article><article className="leader-card reveal-item"><img src={img.ceo} alt="Sohaib Hassan" /><div><small>CHIEF EXECUTIVE</small><h3>Sohaib Hassan</h3><p>Carrying a proven engineering culture into sustainable communities designed for modern, considered living.</p></div></article></div></section>
    <section id="location" className="showcase-section reveal-section"><div className="showcase-heading"><p className="section-kicker">05 / EXPLORE THE COMMUNITY</p><h2>MORE THAN<br /><em>A PLOT.</em></h2><p>Royal Swiss City is planned around the feeling of arriving somewhere complete. Each layer of the neighbourhood is designed to make daily life more fluid, more social, and more connected to the landscape.</p></div><div className="scroll-hint">← SWIPE TO EXPLORE →</div><div className="showcase-rail">{communityCards.map((card, i) => <article className="showcase-card" key={card.title}><img src={card.image} alt={card.title} /><div><span>0{i + 1} / 03</span><h3>{card.title}</h3><p>{card.body}</p><a href="#highlights">EXPLORE <ChevronRight size={13} /></a></div></article>)}</div></section>
    <section id="highlights" className="features-section reveal-section"><p className="section-kicker">06 / THE DETAILS OF A COMPLETE LIFE</p><h2>CONSIDERED<br /><em>AT EVERY SCALE.</em></h2><p className="features-intro">The difference is in the details you notice first — and the ones you only appreciate over time. A secure arrival, a shaded boulevard, a walkable service, an open place to pause. Together, they make a neighbourhood feel instinctive.</p><div className="feature-grid">{features.map((feature, i) => <article className="feature reveal-item" key={feature} style={{ transitionDelay: `${(i % 4) * 70}ms` }}><span>0{i + 1}</span><h3>{feature}</h3><p>{["A calm, professionally managed setting with controlled access and a sense of arrival.", "Energy-conscious infrastructure that supports a more efficient everyday life.", "Open corridors, water, and landscape shaping the mood of the neighbourhood.", "Wide streets and pedestrian routes designed for unhurried movement.", "Thoughtful provision for the things families need as life grows.", "Services and retail planned to stay close to home.", "Room for sport, play, and the simple pleasure of being outdoors.", "Reliable systems designed to make modern living feel effortless."][i]}</p></article>)}</div></section>
    <section id="faq" className="sustainability-section reveal-section"><div className="sustainability-image"><img src={img.green} alt="Royal Swiss City green energy and sustainable infrastructure" /></div><div className="sustainability-copy"><p className="section-kicker">07 / A LIGHTER WAY TO LIVE</p><h2>GREEN IS NOT<br /><em>A FEATURE.</em></h2><p>It is a way of thinking about the future. Royal Swiss City brings green energy, responsible water systems, and an urban-forest setting into the same vision — a community that runs efficiently and leaves room for nature to remain part of daily life.</p><p>The result is not a promise of perfection. It is a more thoughtful starting point for the generations who will live here next.</p><div className="eco-tags"><span>GREEN ENERGY</span><span>WATER RECYCLING</span><span>URBAN FOREST</span></div></div></section>
    <section id="partner" className="partner-strip reveal-section"><img src={img.partnership} alt="Royal Swiss City partnership network" /><div><p className="section-kicker">08 / PARTNER WITH US</p><h2>A PLACE WORTH<br /><em>REPRESENTING.</em></h2><p>Join the Royal Swiss City partner network with a clear story to tell, a considered community to represent, and the support to guide your clients toward a more meaningful address.</p><a className="outline-cta" href="#enquire">APPLY FOR PARTNERSHIP</a></div></section>
    <section id="enquire" className="enquire-section reveal-section"><p className="section-kicker">FIND YOUR PLACE IN THE STORY</p><h2>MAKE ROOM<br /><em>FOR WHAT’S NEXT.</em></h2><p>Tell us what you are looking for — a place to live, a place to invest, or a partnership built around Lahore’s next chapter. Our team will share the right details, at the right pace.</p><div><a href="tel:+9242111777588">042 111 777 588</a><a href="mailto:royalswisscity@gmail.com">royalswisscity@gmail.com</a></div></section>
    <footer className="walk-footer reveal-section"><Logo /><div className="footer-accordions">{footerLinks.map(item => <div className={openFooter === item ? "open" : ""} key={item}><button onClick={() => setOpenFooter(openFooter === item ? null : item)}>{item}<ChevronDown size={14} /></button>{openFooter === item && <p style={{ whiteSpace: "pre-line" }}>{footerDescriptions[item as keyof typeof footerDescriptions]}</p>}</div>)}</div><div className="footer-socials"><a href="https://instagram.com/royalswisscity" target="_blank" rel="noopener noreferrer" title="Instagram"><Instagram size={24} /></a><a href="https://facebook.com/royalswisscity" target="_blank" rel="noopener noreferrer" title="Facebook"><Facebook size={24} /></a><a href="https://tiktok.com/@royalswisscity" target="_blank" rel="noopener noreferrer" title="TikTok"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.68v13.67a2.4 2.4 0 0 1-2.4 2.4 2.4 2.4 0 0 1-2.4-2.4 2.4 2.4 0 0 1 2.4-2.4c.34 0 .67.05.98.15V9.41a5.81 5.81 0 0 0-.98-.08 6.04 6.04 0 0 0-6.04 6.04 6.04 6.04 0 0 0 6.04 6.04 6.04 6.04 0 0 0 6.04-6.04v-3.1a7.7 7.7 0 0 0 3.77 1.01V9.81a4.77 4.77 0 0 1-.77-.06z"/></svg></a><a href="https://linkedin.com/company/royalswisscity" target="_blank" rel="noopener noreferrer" title="LinkedIn"><Linkedin size={24} /></a><a href="https://youtube.com/@royalswisscity" target="_blank" rel="noopener noreferrer" title="YouTube"><Youtube size={24} /></a><a href="https://x.com/royalswisscity" target="_blank" rel="noopener noreferrer" title="X"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24h-6.637l-5.1-6.694-5.867 6.694h-3.306l7.733-8.835L2.25 2.25h6.814l4.882 6.45L18.244 2.25zM17.083 18.386h1.83L6.959 4.155H5.049l12.034 14.231z"/></svg></a></div><div className="footer-contact"><b>Where life happens.</b><span>© 2026 ROYAL SWISS CITY · PRIVACY POLICY · SITEMAP</span></div></footer>

    <div className={`mobile-menu ${menuOpen ? "open" : ""}`}><div className="mobile-menu__top"><button onClick={() => setMenuOpen(false)} aria-label="Close"><ChevronDown size={22} /></button><button onClick={() => setMenuOpen(false)} aria-label="Close"><X size={22} /></button></div><div className="mobile-menu__links">{navMobile.map(item => { const href = item === "DEVELOPER" ? "/developer" : item === "PROJECTS" ? "/projects" : item === "HOME" ? "/" : `#${item.toLowerCase().replaceAll(" ", "-")}`; return <a href={href} onClick={() => setMenuOpen(false)} key={item}>{item}</a> })}</div><div className="mobile-menu__bottom"><Logo /><span>ROYAL SWISS CITY</span></div></div>
  </main>
}

